### ISSUE TITLE
Component hierarchy from devices.xml is lost

### ISSUE THREAD

**Issue by SergeyGulik** [TrakHound/MTConnect.NET#25]
Hi Patrick,

At the moment when probe arrives all components are placed on the first level of hierarchy. 
![image](https://user-images.githubusercontent.com/10059586/169792290-369e8318-5e0a-4d13-aad7-ae1b1acaf6b6.png)
So the structure is lost. I cannot figure out who is child of whom.
I found that you was trying to track hierarchy in public void AssignTypePaths(), but completely commented out this code in 0e50b3ba0c3403b4c86f5813944cf991ec523c38
Instead of just fixing component hierarchy I decided to ask what are your thoughts/ideas? How you saw it implemented?

Best regards,
Sergii

**Comment by PatrickRitchie** [comment]
@SergeyGulik The Components should form a hierarchy and I haven't seen the issue of them being read as flat before.

The expected behavior is shown below where Device contains Axes & Controller and Controller contains two Paths:
![image](https://user-images.githubusercontent.com/13772118/169835676-9103e35b-2149-4a94-8a68-318add92179a.png)

The AssignTypePaths() method was from an older version of MTConnect.NET and I couldn't decide whether to leave it in or not as it shouldn't be needed (assuming everything else if working correctly) but could possibly be useful to show something like breadcrumbs in a UI. I will add this back in on the next release.

I would be curious to see what the Probe XML looks like that you read from to get the result you showed. It looks like the Components other than Axes & Controller are read as a 'generic' Component instead of a derived class based on the Type. 

-Patrick

**Comment by SergeyGulik** [comment]
Hi Patrick,
I apologize. There was no bug there. All components are in place.
Best regards,
Sergii.
